### ISSUE TITLE
Weapon type Splatanus will be split.

### ISSUE THREAD

**Issue by niyari** [cesaregarza/SplatTop#33]
In Japanese, parts of Splatanas seem to be classified as undefined.
![image](https://github.com/user-attachments/assets/84ff6332-b4c2-4654-9a74-a247b5d9e2ab)

en (Correct)
![image](https://github.com/user-attachments/assets/c5a3cbdd-0a03-45d6-99c6-53d8929b5b96)

**Comment by cesaregarza** [comment]
Thank you, I’ll investigate and solve later today

**Comment by cesaregarza** [comment]
This has been solved by updating the data lying in the s3 bucket, and will take effect during the next scheduled update of the game translation data
